name: Claude Code

on:
  issues:
    types: [labeled]

jobs:
  ai-developer:
    if: |
      (github.event_name == 'issues' &&  contains(github.event.issue.labels.*.name, 'assigned-to-ai-developer'))
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      issues: write
      id-token: write
      actions: read
    steps:
      - name: Set env
        run: echo "ANTHROPIC_BASE_URL=$(echo ${{ secrets.ANTHROPIC_BASE_URL }})" >> $GITHUB_ENV

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Run Claude Code
        id: claude
        uses: anthropics/claude-code-action@v1
        with:
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          label_trigger: "assigned-to-ai-developer"
          claude_args: |
            --max-turns 3
          custom_instructions: |
            Use branch prefix: claude-agent-
            If the branch already exists, continue working on it, that means you already worked on this issue, and now continue working on it and making changes and fixes.
            Push your changes to the branch and verify that the branch is found before done
            I need you to check if the branch is live - no need for PR, make sure the branch you made and committed all the changes to is there
