name: Claude Code

on:
  issues:
    types: [labeled]

jobs:
  ai-developer:
    if: |
      (github.event_name == 'issues' &&  contains(github.event.issue.labels.*.name, 'assigned-to-ai-developer'))
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      issues: write
      id-token: write
      actions: read
    steps:
      - name: Set env
        run: echo "ANTHROPIC_BASE_URL=$(echo ${{ secrets.ANTHROPIC_BASE_URL }})" >> $GITHUB_ENV

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Run Claude Code
        id: claude
        uses: anthropics/claude-code-action@v1
        with:
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          label_trigger: "assigned-to-ai-developer"
          claude_args: |
            --max-turns 3

      - name: Push branch if Claude made commits
        if: always() && steps.claude.outcome == 'success'
        run: |
          git push -u origin HEAD || echo "Push failed (may already be pushed)"
